---
title: "Toronto Restaurant Locations"
output:
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

## Restaurant Info
Restaurant information is pulled from [yelp](www.yelp.ca) using the fusion [api](https://www.yelp.ca/developers/documentation/v3)

Dealing with the Oauth authorisation used by yelp isn't straightforward in R, so I used a python script to do this. Info is saved in a csv, which is then loaded into R

```{r loaddata}
data<-read.csv('yelpData.csv')
data[1:2,]
dim(data)
```

Make a map!

```{r makemap,warning=FALSE}
# load libraries
library(leaflet)
library(RColorBrewer)
library(htmltools)
# set up marker colours
pal<-colorFactor('Set1',domain=levels(data$category))

#popup content
data$content<-paste(sep='<br/>',paste(sep='','<a href="https://www.yelp.ca/biz/',data$yelpid,'">',data$name,'</a>'),data$rating,paste(data$reviews,'reviews'))


data$category <- as.factor(data$category)
data$popupContent<-paste(sep='<br/>',)
map<- leaflet(data=data) %>% setView(lng = -79.4, lat = 43.65, zoom = 12) %>% addTiles() %>% 
    addCircleMarkers(color=~pal(category),
    stroke=FALSE,
    fillOpacity=~rating/5.0,
    # clusterOptions=markerClusterOptions(),
    label=~name, #htmlEscape(name)

    )
map
```


